arrowParens = "avoid"
bracketSpacing = true
endOfLine = "auto"
printWidth = 80
singleQuote = false
tabWidth = 2
trailingComma = "all"

overrides = [
  { files = ["*.rs"], options = { tabWidth = 4}}
]
