name: "CI"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test_nswap:
    runs-on: ubuntu-latest
    container:
      image: rust:1.56.1
      env:
        RUSTFLAGS: -C link-arg=-s
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update && apt-get install -y git less vim clang && \
          make rust-setup && \
          make test
